### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shadowTW** [chaun14/invite-manager-bot#13]
Why the commands are not working, and .botstatus it's glitched

**Comment by chaun14** [comment]
hello can i have some logs or screenshots?

**Comment by shadowTW** [comment]
yes wait

**Comment by shadowTW** [comment]
![Capture](https://user-images.githubusercontent.com/64441627/101660089-11c2cc00-3a47-11eb-8646-4a5e3d8bd965.PNG)
![Capture2](https://user-images.githubusercontent.com/64441627/101660092-125b6280-3a47-11eb-8207-db4d0efc7278.PNG)

**Comment by chaun14** [comment]
It's a known bug. Use `npm run dev` to start the bot without the controller

**Comment by shadowTW** [comment]
![Capture3](https://user-images.githubusercontent.com/64441627/101664744-7f252b80-3a4c-11eb-9ad6-68ffa806dad8.PNG)
the bot works on glitch.com?

**Comment by chaun14** [comment]
idk. It isn't made for and it needs a mysql database

**Comment by SyntaxDragon** [comment]
Glitch can run the bot and I see no issues with actually running the bot minus the long wait for it to be compiled, personally, if you're using glitch it's unlikely you have a server for rabbitmq or MySQL which are needed to run the bot.  You would also need to make sure that you don't make any changes on glitch otherwise you're constantly rebuilding your bot. Personally use the main instance provided or get a server.

**Comment by chaun14** [comment]
Yes it may work on platforms like glitch but it's more complicated than running it on a basic vps with mysql and other dependencies installed on.

**Comment by chaun14** [comment]
It was an issue with the controller fixed in the last commit https://github.com/chaun14/invite-manager-bot/commit/49c160006805b3d8ff969d29915c8745911ec700

updating the code should fix the problem
